# Site settings
title: tekkie
#email: ain@flashbit.net
description: Technology blog by Ain Tohvri, CTO at Savings United, leading voucher code solution for premium publishers. Contributor and maintainer of various FOSS projects.
baseurl: ""
url: "https://tekkie.flashbit.net"
locale: en_GB
twitter_username: tekkie
github_username: ain
facebook_username: ain.tohvri
linkedin_username: aintohvri
user_image: /assets/ain.png

# Build settings
markdown: kramdown
permalink: /:categories/:title
gems:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-mentions
paginate: 10
include:
  - _pages
exclude:
  - node_modules/
  - Gemfile*
  - package.json
  - npm-debug.log
  - CNAME
  - README.md
  - packafe-lock.json
google_analytics: UA-590376-4
facebook_app_id: 133041104144029
jekyll-mentions:
  base_url: https://twitter.com
