# Site settings
title: tekkie
#email: ain@flashbit.net
description: >
  Technology blog of <span itemscope itemprop="author" itemtype="http://schema.org/Person"><em class="emphasised" itemprop="name">Ain Tohvri</em>, <span itemprop="jobTitle">CTO</span> at <span itemprop="worksFor">Savings United</span>, international network of digital coupon marketplaces. Contributor and maintainer of various Free and Open Source Software projects.<br><br>Cross-browser testing of this site and its selected works is powered by<br><br><a href="https://www.browserstack.com" title="BrowserStack"><img src="/assets/browserstack.svg" height="32px" alt="BrowserStack" id="browserstack"></a>
baseurl: ""
url: "https://tekkie.flashbit.net"
locale: en_GB
twitter_username: tekkie
github_username: ain
facebook_username: ain.tohvri

# Build settings
markdown: kramdown
permalink: /:categories/:title
gems:
  - jekyll-paginate
  - jekyll-sitemap
paginate: 10
exclude:
  - node_modules/
  - Gemfile*
  - package.json
  - npm-debug.log

google_analytics: UA-590376-4
