# Site settings
title: tekkie
#email: ain@flashbit.net
description: Technology blog of Ain Tohvri, CTO at Savings United, international network of digital coupon marketplaces. Contributor and maintainer of various FOSS projects.
baseurl: ""
url: "https://tekkie.flashbit.net"
locale: en_GB
twitter_username: tekkie
github_username: ain
facebook_username: ain.tohvri
linkedin_username: aintohvri

# Build settings
markdown: kramdown
permalink: /:categories/:title
gems:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
paginate: 10
include:
  - _pages
exclude:
  - node_modules/
  - Gemfile*
  - package.json
  - npm-debug.log
  - CNAME
  - README.md
  - packafe-lock.json
google_analytics: UA-590376-4
