# Site settings
title: tekkie
#email: ain@flashbit.net
description: Technology blog by Ain Tohvri. Applying DevOps to solve human problems by code. Contributor & maintainer of various FOSS projects.
baseurl: ""
url: "https://tekkie.dev"
locale: en_GB
twitter_username: tekkie
github_username: ain
linkedin_username: aintohvri
user_image: /assets/ain.jpg
logo: /assets/ain.jpg

# Build settings
markdown: kramdown
permalink: /:categories/:title
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-mentions
  - jekyll-seo-tag
  - jekyll-gist
paginate: 5
include:
  - _pages
exclude:
  - CNAME
  - README.md
jekyll-mentions:
  base_url: https://twitter.com
twitter:
  username: tekkie
  card: summary
social:
  name: Ain Tohvri
  links:
    - https://twitter.com/tekkie
    - https://www.linkedin.com/in/aintohvri
    - https://github.com/ain
