# Site settings
title: tekkie
#email: ain@flashbit.net
description: >
  <span itemscope itemprop="author" itemtype="http://schema.org/Person">Tech blog of <span itemprop="name">Ain Tohvri</span>, <span itmeprop="jobTitle">Sr. Software Engineer</span> at <a href="http://twitter.com/i_pioneers">@<span itemprop="worksFor">i_pioneers</span></a> <span itemprop="workLocation homeLocation">Hamburg</span>, partner at <span itemprop="owns">OÜ Flashbit</span>. Supporter of open standards, Free Software. Involved in various FOSS projects.<br>Core Team member of <a href="http://twitter.com/assemblejs">@<span itemprop="memberOf">assemblejs</a></span>.
baseurl: ""
url: "http://tekkie.flashbit.net"
twitter_username: tekkie
github_username:  ain

# Build settings
markdown: kramdown
permalink: /:categories/:title
gems:
  - jekyll-paginate
paginate: 10
exclude:
  - node_modules/
  - Gemfile*
  - package.json
  - npm-debug.log

google_analytics: UA-590376-4
